{
  "uuid": "96ffe57b-5aa6-47cb-9b1f-8b5d574e9430",
  "children": [
    "5fbf6baf-0e91-439c-83ad-139ca83c25d7"
  ],
  "befores": [
    {
      "name": "_Class__pytest_setup_method",
      "status": "broken",
      "statusDetails": {
        "message": "selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:9222\nfrom chrome not reachable\n\n",
        "trace": "  File \"d:\\python38\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 908, in call_fixture_func\n    fixture_result = next(generator)\n  File \"d:\\python38\\lib\\site-packages\\_pytest\\python.py\", line 824, in xunit_setup_method_fixture\n    _call_with_optional_argument(func, method)\n  File \"d:\\python38\\lib\\site-packages\\_pytest\\python.py\", line 732, in _call_with_optional_argument\n    func(arg)\n  File \"D:\\PycharmProjects\\HogwartsSDET15\\testing\\test_qiyeweix.py\", line 17, in setup_method\n    self.driver = webdriver.Chrome(options=options)\n  File \"d:\\python38\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 76, in __init__\n    RemoteWebDriver.__init__(\n  File \"d:\\python38\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"d:\\python38\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 252, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"d:\\python38\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"d:\\python38\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"
      },
      "start": 1604475867546,
      "stop": 1604475931611
    }
  ],
  "start": 1604475867546,
  "stop": 1604475931705
}